application: kaodatavizzy
version: 1
runtime: python
api_version: 1

handlers:

- url: /(.*\.(gif|png|jpg|jpeg|ico|js|css|json|csv|txt|svg|woff2|woff|eot|ttf|mp4))
  static_files: \1
  upload: (.*\.(gif|png|jpg|jpeg|ico|js|css|json|csv|txt|svg|woff2|woff|eot|ttf|mp4))


- url: .*
  script: main.py
